//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Geoapify.Resources.Services {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeoapifyGeocoding {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoapifyGeocoding() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Geoapify.Resources.Services.GeoapifyGeocoding", typeof(GeoapifyGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Geoapify uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the text or at least one address component must be provided..
        /// </summary>
        internal static string Invalid_Address {
            get {
                return ResourceManager.GetString("Invalid Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The biases are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Biases {
            get {
                return ResourceManager.GetString("Invalid Biases", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The reverse geocoding coordinate cannot be null..
        /// </summary>
        internal static string Invalid_Coordinate {
            get {
                return ResourceManager.GetString("Invalid Coordinate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filters are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Filters {
            get {
                return ResourceManager.GetString("Invalid Filters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The language is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Language {
            get {
                return ResourceManager.GetString("Invalid Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The limit is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Limit {
            get {
                return ResourceManager.GetString("Invalid Limit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The text query cannot be null or empty..
        /// </summary>
        internal static string Invalid_Text {
            get {
                return ResourceManager.GetString("Invalid Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The location type is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Type {
            get {
                return ResourceManager.GetString("Invalid Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Geoapify parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
