//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.ArcGIS.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArcGISGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArcGISGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.ArcGIS.Resources.Services.ArcGISGeocoding", typeof(ArcGISGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the ArcGIS uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address attributes cannot be null or empty..
        /// </summary>
        internal static string Invalid_Address_Attributes {
            get {
                return ResourceManager.GetString("Invalid Address Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Category {
            get {
                return ResourceManager.GetString("Invalid Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature types are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Feature_Types {
            get {
                return ResourceManager.GetString("Invalid Feature Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language code is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Language_Code {
            get {
                return ResourceManager.GetString("Invalid Language Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Location {
            get {
                return ResourceManager.GetString("Invalid Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location cannot be null..
        /// </summary>
        internal static string Invalid_Location_Error {
            get {
                return ResourceManager.GetString("Invalid Location Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location type is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Location_Type {
            get {
                return ResourceManager.GetString("Invalid Location Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum locations is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Maximum_Locations {
            get {
                return ResourceManager.GetString("Invalid Maximum Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The out spatial reference is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Out_Spatial_Reference {
            get {
                return ResourceManager.GetString("Invalid Out Spatial Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preferred label value is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Preferred_Label_Value {
            get {
                return ResourceManager.GetString("Invalid Preferred Label Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search extent is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Search_Extent {
            get {
                return ResourceManager.GetString("Invalid Search Extent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The single line address cannot be null or empty..
        /// </summary>
        internal static string Invalid_Single_Address_Line {
            get {
                return ResourceManager.GetString("Invalid Single Address Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source country is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Source_Country {
            get {
                return ResourceManager.GetString("Invalid Source Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text cannot be null or empty..
        /// </summary>
        internal static string Invalid_Text {
            get {
                return ResourceManager.GetString("Invalid Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArcGIS parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
