//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.OpenRouteService.Resources.Services {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenRouteServiceGeocoding {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenRouteServiceGeocoding() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.OpenRouteService.Resources.Services.OpenRouteServiceGeocoding", typeof(OpenRouteServiceGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create the OpenRouteService Geocoding uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one address component must be provided..
        /// </summary>
        internal static string Invalid_Address_Components {
            get {
                return ResourceManager.GetString("Invalid Address Components", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The boundary circle is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Boundary_Circle {
            get {
                return ResourceManager.GetString("Invalid Boundary Circle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The boundary countries are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Boundary_Countries {
            get {
                return ResourceManager.GetString("Invalid Boundary Countries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The boundary GID is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Boundary_Gid {
            get {
                return ResourceManager.GetString("Invalid Boundary Gid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The boundary rectangle is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Boundary_Rect {
            get {
                return ResourceManager.GetString("Invalid Boundary Rect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The focus point is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Focus_Point {
            get {
                return ResourceManager.GetString("Invalid Focus Point", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The layers are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Layers {
            get {
                return ResourceManager.GetString("Invalid Layers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The reverse geocoding point cannot be null..
        /// </summary>
        internal static string Invalid_Point {
            get {
                return ResourceManager.GetString("Invalid Point", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The size is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Size {
            get {
                return ResourceManager.GetString("Invalid Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sources are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Sources {
            get {
                return ResourceManager.GetString("Invalid Sources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The text query cannot be null or empty..
        /// </summary>
        internal static string Invalid_Text {
            get {
                return ResourceManager.GetString("Invalid Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The OpenRouteService Geocoding parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
