//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Here.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HereGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HereGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Here.Resources.Services.HereGeocoding", typeof(HereGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the HERE uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The at coordinates cannot be null..
        /// </summary>
        internal static string Invalid_At {
            get {
                return ResourceManager.GetString("Invalid At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The at is invalid and will not be used..
        /// </summary>
        internal static string Invalid_At_Debug {
            get {
                return ResourceManager.GetString("Invalid At Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of bounding parameters is not valid..
        /// </summary>
        internal static string Invalid_Bounding_Parameters {
            get {
                return ResourceManager.GetString("Invalid Bounding Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The categories are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Categories {
            get {
                return ResourceManager.GetString("Invalid Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id cannot be null..
        /// </summary>
        internal static string Invalid_Id {
            get {
                return ResourceManager.GetString("Invalid Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in bounding box is invalid and will not be used..
        /// </summary>
        internal static string Invalid_In_Bounding_Box {
            get {
                return ResourceManager.GetString("Invalid In Bounding Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in circle is invalid and will not be used..
        /// </summary>
        internal static string Invalid_In_Circle {
            get {
                return ResourceManager.GetString("Invalid In Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in country is invalid and will not be used..
        /// </summary>
        internal static string Invalid_In_Country {
            get {
                return ResourceManager.GetString("Invalid In Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Limit {
            get {
                return ResourceManager.GetString("Invalid Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Name {
            get {
                return ResourceManager.GetString("Invalid Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The qualified query is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Qualified_Query {
            get {
                return ResourceManager.GetString("Invalid Qualified Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Query {
            get {
                return ResourceManager.GetString("Invalid Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both query and qualifiedquery cannot be null or empty..
        /// </summary>
        internal static string Invalid_Query_And_Qualified_Query {
            get {
                return ResourceManager.GetString("Invalid Query And Qualified Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query cannot be null or empty..
        /// </summary>
        internal static string Invalid_Query_Error {
            get {
                return ResourceManager.GetString("Invalid Query Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Route {
            get {
                return ResourceManager.GetString("Invalid Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terms limit is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Terms_Limit {
            get {
                return ResourceManager.GetString("Invalid Terms Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HERE parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
