//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Google.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Google.Resources.Services.GoogleGeocoding", typeof(GoogleGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Google uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address cannot be null or empty..
        /// </summary>
        internal static string Invalid_Address {
            get {
                return ResourceManager.GetString("Invalid Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounds are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Bounds {
            get {
                return ResourceManager.GetString("Invalid Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The components are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Components {
            get {
                return ResourceManager.GetString("Invalid Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates cannot be null..
        /// </summary>
        internal static string Invalid_Coordinates {
            get {
                return ResourceManager.GetString("Invalid Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Fields {
            get {
                return ResourceManager.GetString("Invalid Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input cannot be null or empty..
        /// </summary>
        internal static string Invalid_Input {
            get {
                return ResourceManager.GetString("Invalid Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Input_Info {
            get {
                return ResourceManager.GetString("Invalid Input Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input type must be valid..
        /// </summary>
        internal static string Invalid_Input_Type {
            get {
                return ResourceManager.GetString("Invalid Input Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Keyword {
            get {
                return ResourceManager.GetString("Invalid Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Language {
            get {
                return ResourceManager.GetString("Invalid Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location cannot be null..
        /// </summary>
        internal static string Invalid_Location {
            get {
                return ResourceManager.GetString("Invalid Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location bias is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Location_Bias {
            get {
                return ResourceManager.GetString("Invalid Location Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location bias type is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Location_Bias_Type {
            get {
                return ResourceManager.GetString("Invalid Location Bias Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location types are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Location_Types {
            get {
                return ResourceManager.GetString("Invalid Location Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum price is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Maximum_Price {
            get {
                return ResourceManager.GetString("Invalid Maximum Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum price is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Minimum_Price {
            get {
                return ResourceManager.GetString("Invalid Minimum Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Offset {
            get {
                return ResourceManager.GetString("Invalid Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Origin {
            get {
                return ResourceManager.GetString("Invalid Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page token is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Page_Token {
            get {
                return ResourceManager.GetString("Invalid Page Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place id cannot be null or invalid..
        /// </summary>
        internal static string Invalid_PlaceId {
            get {
                return ResourceManager.GetString("Invalid PlaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query cannot be null or invalid..
        /// </summary>
        internal static string Invalid_Query {
            get {
                return ResourceManager.GetString("Invalid Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radius must be greater than 0..
        /// </summary>
        internal static string Invalid_Radius {
            get {
                return ResourceManager.GetString("Invalid Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radius is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Radius_Value {
            get {
                return ResourceManager.GetString("Invalid Radius Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rank by is invalid and will not be used..
        /// </summary>
        internal static string Invalid_RankBy {
            get {
                return ResourceManager.GetString("Invalid RankBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radius must not be greater than 0 on a rank by distance request..
        /// </summary>
        internal static string Invalid_RankBy_Distance_Radius {
            get {
                return ResourceManager.GetString("Invalid RankBy Distance Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword or type must be specified when ranking by distance..
        /// </summary>
        internal static string Invalid_RankBy_Distance_Request {
            get {
                return ResourceManager.GetString("Invalid RankBy Distance Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Region {
            get {
                return ResourceManager.GetString("Invalid Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result types are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Result_Types {
            get {
                return ResourceManager.GetString("Invalid Result Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session token is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Session_Token {
            get {
                return ResourceManager.GetString("Invalid Session Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Type {
            get {
                return ResourceManager.GetString("Invalid Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Types {
            get {
                return ResourceManager.GetString("Invalid Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
