//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.MapQuest.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapQuestGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapQuestGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.MapQuest.Resources.Services.MapQuestGeocoding", typeof(MapQuestGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the MapQuest uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounding box is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Bounding_Box {
            get {
                return ResourceManager.GetString("Invalid Bounding Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intl mode is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Intl_Mode {
            get {
                return ResourceManager.GetString("Invalid Intl Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location cannot be null or invalid..
        /// </summary>
        internal static string Invalid_Location {
            get {
                return ResourceManager.GetString("Invalid Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum results are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Maximum_Results {
            get {
                return ResourceManager.GetString("Invalid Maximum Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MapQuest parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
