//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.MapBox.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapBoxGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapBoxGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.MapBox.Resources.Services.MapBoxGeocoding", typeof(MapBoxGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the MapBox uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounding box is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Bounding_Box {
            get {
                return ResourceManager.GetString("Invalid Bounding Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates cannot be null..
        /// </summary>
        internal static string Invalid_Coordinate {
            get {
                return ResourceManager.GetString("Invalid Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The countries are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Countries {
            get {
                return ResourceManager.GetString("Invalid Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The languages are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Languages {
            get {
                return ResourceManager.GetString("Invalid Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proximity is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Proximity {
            get {
                return ResourceManager.GetString("Invalid Proximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query cannot be null or empty..
        /// </summary>
        internal static string Invalid_Query {
            get {
                return ResourceManager.GetString("Invalid Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types are invalid and will not be used..
        /// </summary>
        internal static string Invalid_Types {
            get {
                return ResourceManager.GetString("Invalid Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MapBox parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
