//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Trimble.Resources.Services {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrimbleGeocoding {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrimbleGeocoding() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Trimble.Resources.Services.TrimbleGeocoding", typeof(TrimbleGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Trimble Maps uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one address field must be provided..
        /// </summary>
        internal static string Invalid_Address {
            get {
                return ResourceManager.GetString("Invalid Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The coordinate cannot be null or invalid..
        /// </summary>
        internal static string Invalid_Coordinate {
            get {
                return ResourceManager.GetString("Invalid Coordinate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Trimble Maps parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
