//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Bing.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BingGeocoding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BingGeocoding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Bing.Resources.Services.BingGeocoding", typeof(BingGeocoding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include entity types will not be used..
        /// </summary>
        internal static string Do_Not_Include_Entity_Types {
            get {
                return ResourceManager.GetString("Do Not Include Entity Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include neighbourhood will not be used..
        /// </summary>
        internal static string Do_Not_Include_Neighbourhood {
            get {
                return ResourceManager.GetString("Do Not Include Neighbourhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include types will not be used..
        /// </summary>
        internal static string Do_Not_Include_Types {
            get {
                return ResourceManager.GetString("Do Not Include Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Bing uri..
        /// </summary>
        internal static string Failed_To_Create_Uri {
            get {
                return ResourceManager.GetString("Failed To Create Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address information cannot all be null or empty..
        /// </summary>
        internal static string Invalid_Address_Information {
            get {
                return ResourceManager.GetString("Invalid Address Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address line is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Address_Line {
            get {
                return ResourceManager.GetString("Invalid Address Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administration district is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Administration_District {
            get {
                return ResourceManager.GetString("Invalid Administration District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country region is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Country_Region {
            get {
                return ResourceManager.GetString("Invalid Country Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input cannot be null or empty..
        /// </summary>
        internal static string Invalid_Input {
            get {
                return ResourceManager.GetString("Invalid Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The locality is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Locality {
            get {
                return ResourceManager.GetString("Invalid Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum result is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Maximum_Results {
            get {
                return ResourceManager.GetString("Invalid Maximum Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point cannot be null..
        /// </summary>
        internal static string Invalid_Point {
            get {
                return ResourceManager.GetString("Invalid Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code is invalid and will not be used..
        /// </summary>
        internal static string Invalid_Postal_Code {
            get {
                return ResourceManager.GetString("Invalid Postal Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query cannot be null or empty..
        /// </summary>
        internal static string Invalid_Query {
            get {
                return ResourceManager.GetString("Invalid Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing parameters are null..
        /// </summary>
        internal static string Null_Parameters {
            get {
                return ResourceManager.GetString("Null Parameters", resourceCulture);
            }
        }
    }
}
